name: FastEat Pipeline

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  # 1. Valida sintaxis
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npm run lint

  # 2. Revisa seguridad
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm audit --audit-level=high

  # 3. Simulación E2E de carrito
  staging:
    needs: [build-and-lint, security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npm run test:e2e

  # 4. Despliegue al aprobar release
  production:
    needs: [staging]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Desplegando en producción tras aprobar release..."